swagger: "2.0"
info:
  version: 1.0.0
  title: tkreqres
  description: tkreqres
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      parameters:
        - name: x-auth-token
          in: header
          required: true
          type: string
          description: Firebase access token
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: x-auth-token
          in: header
          required: true
          type: string
          description: Firebase access token

        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{_id}:
    get:
      tags:
        - Examples
      parameters:
        - name: x-auth-token
          in: header
          required: true
          type: string
          description: Firebase access token
          
        - name: _id
          in: path
          required: true
          description: The _id of the example to retrieve
          type: string
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification